# This composes create a new postgres container.
version: '3.7'
services:
  postgres:
    image: postgres:15.4
    restart: on-failure
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data